import { Project } from '@/types';

export const projectsData: Project[] = [
  {
    id: 'project-1',
    slug: 'labshare-unpam',
    title: 'LabShare UNPAM',
    description: 'A specialized internal marketplace and product catalog portal for Universitas Pamulang, bridging campus products, travel services, and IT devices under a single unified web platform.',
    summary: 'Developed an internal marketplace portal for Universitas Pamulang to manage and showcase campus-wide products.',
    challenge: 'Consolidating diverse product categories (from IT devices to Umroh/Travel services) into a unified catalog structure.',
    contribution: 'Designed and built robust backend REST APIs using Laravel, and integrated them seamlessly with a React frontend.',
    key_features: ['REST API Integration', 'Product Cataloging', 'Search & Filtering', 'Responsive Design'],
    category: 'Fullstack',
    image_url: '/projects/labshare.png',
    tech_stack: ['Laravel', 'React', 'MySQL', 'TailwindCSS'],
    demo_url: 'https://labshare.unpam.ac.id/',
    repo_url: null,
    sort_order: 1,
    additional_images: [],
    created_at: new Date().toISOString(),
  },
  {
    id: 'project-2',
    slug: 'company-profile-cms',
    title: 'Corporate CMS Profile',
    description: 'A custom CMS-driven corporate website with optimized SEO and performance metrics for high-speed content delivery.',
    summary: 'Developed a high-performance company profile serving global clients.',
    challenge: 'Achieving 99+ Lighthouse scores while maintaining rich media content.',
    contribution: 'Developed the frontend using Next.js and integrated a Headless CMS for marketing teams.',
    key_features: ['Headless CMS', 'Next.js SSR', 'i18n Support', 'Analytics Dashboard'],
    category: 'Frontend',
    image_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=800&auto=format&fit=crop',
    tech_stack: ['Next.js', 'TypeScript', 'Framer Motion', 'TailwindCSS'],
    demo_url: 'https://demo.com',
    repo_url: 'https://github.com/AriHyuk',
    sort_order: 2,
    additional_images: [],
    created_at: new Date().toISOString(),
  }
];
