import { Project } from '@/types';

export const projectsData: Project[] = [
  {
    id: 'project-1',
    slug: 'labshare-unpam',
    title: 'LabShare UNPAM',
    description: 'A specialized internal marketplace and product catalog portal for Universitas Pamulang, bridging campus products, travel services, and IT devices under a single unified web platform.',
    summary: 'Developed an internal marketplace portal for Universitas Pamulang to manage and showcase campus-wide products.',
    challenge: 'Consolidating diverse product categories (from IT devices to Umroh/Travel services) into a unified catalog structure.',
    contribution: 'Designed and built robust backend REST APIs using Laravel, and integrated them seamlessly with a React frontend.',
    key_features: ['REST API Integration', 'Product Cataloging', 'Search & Filtering', 'Responsive Design'],
    category: 'Fullstack',
    image_url: '/projects/labshare.png',
    tech_stack: ['Laravel', 'React', 'MySQL', 'TailwindCSS'],
    demo_url: 'https://labshare.unpam.ac.id/',
    repo_url: null,
    sort_order: 1,
    additional_images: [],
    created_at: new Date().toISOString(),
  },
  {
    id: 'project-2',
    slug: 'fajar-putra-cikande',
    title: 'Fajar Putra Cikande',
    description: 'A custom CMS-driven corporate website and recruitment portal for PT Fajar Putra Cikande, a trusted business outsourcing partner since 2019.',
    summary: 'Developed a high-performance corporate website and outsourcing portal for PT Fajar Putra Cikande.',
    challenge: 'Creating a highly responsive design with seamless asset loading and premium animations while maintaining fast performance.',
    contribution: 'Designed and developed the frontend using Next.js, optimized media delivery, and integrated a Headless CMS for their marketing team.',
    key_features: ['Headless CMS', 'Next.js SSR', 'Responsive Design', 'Interactive Gallery', 'Partner Showcase'],
    category: 'Frontend',
    image_url: '/projects/fpc.png',
    tech_stack: ['Next.js', 'TypeScript', 'Framer Motion', 'TailwindCSS'],
    demo_url: 'https://www.fajarputracikande.co.id/',
    repo_url: 'https://github.com/AriHyuk',
    sort_order: 2,
    additional_images: [],
    created_at: new Date().toISOString(),
  },
];
